### ISSUE TITLE
[DEV] Generate metadata from SMD and groups

### ISSUE THREAD

**Issue by davidallendj** [OpenCHAMI/cloud-init#22]
## Overview
The `cloud-init` server should query SMD to generate the `meta-data` portion of its payload automatically using information stored in SMD as well as group information stored in the cloud-init service. The SMD serves as the source of truth, providing both node details and group affiliations essential for accurate metadata creation.  The cloud-init service should also support storage of shell script snippets along with group information along with a weighting score which can be added to the cloud-init `user-data` payload as well.

## Requirements

1. **Automatic Meta-Data Generation**:
   - The `cloud-init` server must fetch node-specific data from  SMD to generate the `meta-data` payload dynamically.
   
2. **Group-Based Key/Value Data**:
   - SMD stores information on groups associated with each node.
   - Administrators should be able to add custom key/value pairs within the `cloud-init` server for any group. These values will be attached to nodes belonging to that group within the `meta-data` payload.
   - The payload should be structured such that each group’s key/value data appears under `groups.$groupname.data`.

3. **Group-Based `runcmd` Entries with Weighting**:
   - In addition to key-value pairs, admins may define shell scripts or command sequences (`runcmd` entries) for each group.
   - Each `runcmd` entry can be either a single command or a multi-line script.
   - Each `runcmd` entry has an optional `weighting` value (from `1` to `100`) to control execution order. The default weighting is `50`.
   - Lower weighting values indicate higher priority, ensuring that more critical commands are executed first. Commands with the same weighting execute in their listed order.

4. **Payload Structure**:
   - When generating the `user-data` and `meta-data` payloads for a node, the `cloud-init` server should:
     - Identify groups associated with the node via SMD.
     - Attach any key/value pairs under `groups.$groupname.data`.
     - Include each group’s `runcmd` entries in the `user-data` payload, ordered by `weighting` and clearly annotated with the group name and description for debugging.

5. **Example Group-Level Key/Value Pairs and `runcmd` Entries**:
   - Suppose the following groups, key/value pairs, and `runcmd` entries are configured:

     - **Group: system-update**
       - Key/Value: `{"tier": "base", "environment": "production"}`
       - `runcmd`: 
         ```bash
         apt-get update
         apt-get -y upgrade
         ```
       - `weighting`: `25`

     - **Group: install-nginx**
       - Key/Value: `{"tier": "frontend", "application": "nginx"}`
       - `runcmd`: 
         ```bash
         apt-get -y install nginx
         systemctl enable nginx
         systemctl start nginx
         ```
       - `weighting`: `50`

     - **Group: monitoring**
       - Key/Value: `{"agent": "prometheus", "alerting": "enabled"}`
       - `runcmd`: 
         ```bash
         ufw allow 'Nginx Full'
         ufw enable
         ```
       - `weighting`: `75`

6. **Sample Payloads**:

   - **`meta-data` Payload**:
     ```json
     {
       "instance-id": "i-abcdef123456",
       "local-hostname": "web-node-01",
       "groups": {
         "system-update": {
           "data": {
             "tier": "base",
             "environment": "production"
           }
         },
         "install-nginx": {
           "data": {
             "tier": "frontend",
             "application": "nginx"
           }
         },
         "monitoring": {
           "data": {
             "agent": "prometheus",
             "alerting": "enabled"
           }
         }
       }
     }
     ```

   - **`user-data` Payload**:
     ```yaml
     #cloud-config
     runcmd:
       - "# Group: system-update | Weighting: 25 | Description: System update and upgrade"
       - |
           apt-get update
           apt-get -y upgrade

       - "# Group: install-nginx | Weighting: 50 | Description: Install and start Nginx"
       - |
           apt-get -y install nginx
           systemctl enable nginx
           systemctl start nginx

       - "# Group: monitoring | Weighting: 75 | Description: Configure firewall for monitoring"
       - |
           ufw allow 'Nginx Full'
           ufw enable
     ```

7. **Client Use of Group Data**:
   - After boot, clients can use this group-specific data to trigger specific behaviors based on group associations, enabling dynamic configuration and automation.

**Comment by alexlovelltroy** [comment]
We may want to separate the meta-data portion of this ticket from the runcmd portion and implement meta-data first.

**Comment by alexlovelltroy** [comment]
- [ ] Implement the group-based key/value interface
- [ ] **NOT READY** Implement the group-based user-data interface

We need to talk more to @travisbcotton and other @OpenCHAMI/lanl admins about the right thing to do for user-data.  Is runcmd enough, or should we support everything from https://cloudinit.readthedocs.io/en/latest/explanation/format.html for groups?  How does this impact troubleshooting for nodes with many groups and possibly many `user-data` stanzas?

**Comment by travisbcotton** [comment]
Limiting `user-data` to a set of `runcmd`s seems too restrictive. There are a lot of `cloud-init` modules and it's not clear based on these descriptions if we can do things like `write_files`.   

I would argue we shouldn't restrict what the `user-data` payload can be and leave that up to the system admins. This does a couple of things I think
- Offloads complexity to users of the cloud-init server
- Allows for a lot of flexibility without having to code for that flexibility
- `meta-data` is still generated from groups and data from SMD

A simple example:
Create two groups `x1000` and `compute`  
```json
// x1000 group
{
    "rsyslog_aggregator": "192.168.1.1"
}
// compute group
{
    "rsyslog_aggregator": "192.168.1.100"
}
```

Then you can use jinja2 templates to do the logic on which value should be set, and that logic is provided by admins.
A couple of examples. 
```jinja2
# Remote Logging
action(type="omfwd" target="{{ groups.compute.data.rsyslog_aggregator }}" port="514" protocol="tcp")
```
```jinja2
# Remote Logging
{% if groups.x1000.data.rsyslog_aggregator is defined %}
action(type="omfwd" target="{{ groups.x1000.data.rsyslog_aggregator }}" port="514" protocol="tcp")
{% else %}
action(type="omfwd" target="{{ groups.compute.data.rsyslog_aggregator }}" port="514" protocol="tcp")
{% endif %}
```
Doing this you can even set the priority outside the cloud-init server
```json
// x1000 group
{
    "rsyslog_aggregator": "192.168.1.1"
    "priority": "1"
}
// compute group
{
    "rsyslog_aggregator": "192.168.1.100"
    "priority": "99"
}
```
And use it in a template
```jinja2
{%- set ns = namespace(group="", priority=99) -%}
{%- for group,group_data in groups.items() -%}
	{%- if group_data.data.rsyslog_aggregator is defined -%}
		{%- set priority = group_data.data.priority | int -%}
		{%- if ( priority < ns.priority ) -%}
			{%- set ns.group = group -%}
			{%- set ns.priority = priority -%}
		{%- endif -%}
	{%- endif -%}
{%- endfor -%}
# Remote Logging
action(type="omfwd" target="{{ groups[ns.group].data.rsyslog_aggregator }}" port="514" protocol="tcp")
```
