### ISSUE TITLE
[BUG] Metadata returns an empty list instead of being empty

### ISSUE THREAD

**Issue by alexlovelltroy** [OpenCHAMI/cloud-init#29]
After adding a group to the cloud-init server that only contains user-data information (and not meta-data) information, the group ends up represented in the meta-data anyway as a key and empty list.

```bash
$curl -s $CLOUD_INIT_URL/x1000c1s7b1n0/meta-data
groups:
  ssh: []
```

In the above example `ssh` should not be listed if it is empty.

`groups` should also not be listed if it is empty.

**Comment by davidallendj** [comment]
Would this simply require exporting the `groups` field and adding field tag to this line?
https://github.com/OpenCHAMI/cloud-init/blob/main/internal/memstore/ciMemStore.go#L24

So something like:
```go
type MemStore struct {
	list   map[string]citypes.CI
	Groups map[string]citypes.GroupData `json:"groups,omitempty"`
}
```

**Comment by davidallendj** [comment]
Resolved with https://github.com/OpenCHAMI/cloud-init/pull/33.
